import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :my_app, MyAppWeb.Endpoint,
  url: [host: "example.com", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  force_ssl: [hsts: true],
  http: [port: 4000, transport_options: [socket_opts: [:inet6]]],
  https: [
    port: 4040,
    cipher_suite: :strong,
    transport_options: [socket_opts: [:inet6]]
  ]

# Set path to cert folder
config :my_app, :cert_path, "/home/<YOUR_USERNAME>/site_encrypt_db"

# Set the cert mode so site_encrypt knows to hit live LetsEncrypt
config :my_app, :cert_mode, "production"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: MyApp.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

import_config "prod.secret.exs"
